### ISSUE TITLE
The composer.json     "furqansiddiqui/bip32-keypair-php": "dev-master#57ec344" can't find

### ISSUE THREAD

**Issue by PHPJourney** [furqansiddiqui/ethereum-php#5]
I get furqansiddiqui/ethereum-php 0.1.15 requires furqansiddiqui/bip32-keypair-php dev-master#57ec344 -> found furqansiddiqui/bip32-keypair-php[dev-master] but it does not match your minimum-stability.

**Comment by cmooninfotech** [comment]
1.  Remove vendor folder
2.  Update composer `composer update`
3.  Set your config like this:

```
{
    "name": "erc20-php",
    "require": {
        "php-64bit": "^7.4",
        "furqansiddiqui/ethereum-php": "^0.1.20",
        "furqansiddiqui/erc20-php": "dev-master"
    },
    "minimum-stability": "dev"
}
```
4.   Again update composer `composer update`
